### ISSUE TITLE
`hugo+extended` is updated to plain `hugo`

### ISSUE THREAD

**Issue by foxyseta** [Gelio/go-global-update#28]
Before installing go-global-update, I had a `hugo` installation with the `extended` tag. Whenever `go-global-update` updates `hugo`, the non-`extended` tag is used. I think this kind of tags should be preserved.

**Comment by Gelio** [comment]
Thanks for the issue! I didn't know about build tags before, good to know. I agree that `go-global-update` should preserve tags. I will see if there is a way to get the list of tags used to install a binary.

Resource on build tags (mostly for me for the future): https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags

**Comment by Gelio** [comment]
Yes, looks like `go version -m` includes the tags:

```sh
at 17:44:59 ❯ go version -m $(which hugo) | grep tags
        build   -tags=extended
```

It should be enough to implement this behavior. I will take a stab at it tomorrow.

**Comment by Gelio** [comment]
I have just released https://github.com/Gelio/go-global-update/releases/tag/v0.2.5

Please upgrade `go-global-update` (it should self-update, in fact), and then please give it a try when upgrading `hugo`. You could test it by downgrading `hugo` (installing an older version on purpose) (include build tags), and then run `go-global-update`.

**Comment by foxyseta** [comment]
Yep, now the upgrade from v0.134.1 to v0.134.2 preserves the tag as desired, as specified by the output.

```
Upgrading hugo to v0.134.2 (build tags: extended) ...
```

Thank you so much!

**Comment by Gelio** [comment]
Great, thank you for confirming!
